import { ArrowUpRight, Database, LineChart, Users } from 'lucide-react'

const projects = [
  { number: '01', title: 'Retail Sales Intelligence', type: 'Power BI dashboard', metric: '500K+', metricLabel: 'transactions analyzed', description: 'Built an interactive retail dashboard to reveal revenue trends, product performance, regional demand, and customer behavior across a large transactional dataset.', tags: ['Power BI', 'Excel', 'Data cleaning'], icon: LineChart, tone: 'bg-accent' },
  { number: '02', title: 'Customer Churn Prediction', type: 'Machine learning model', metric: '0.87', metricLabel: 'model accuracy', description: 'Developed a classification model to identify customers at risk of churn, translating model outputs into retention-focused business recommendations.', tags: ['Python', 'Pandas', 'Scikit-learn'], icon: Users, tone: 'bg-secondary' },
  { number: '03', title: 'Data Foundations', type: 'SQL analysis toolkit', metric: '100%', metricLabel: 'query-first thinking', description: 'Designed reusable SQL queries and analysis workflows that turn raw tables into reliable metrics for reporting and better decisions.', tags: ['SQL', 'MySQL', 'Analytics'], icon: Database, tone: 'bg-muted' },
]

export default function Projects() {
  return <section id="work" className="mx-auto max-w-7xl px-6 py-24 lg:px-10 lg:py-32"><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-accent">Selected work / 02</p><h2 className="mt-4 max-w-2xl text-balance font-serif text-5xl leading-none tracking-[-0.04em] text-primary md:text-7xl">Analysis that<br /><em className="text-accent">moves</em> people.</h2></div><p className="max-w-xs text-sm leading-6 text-muted-foreground">A selection of projects where messy information became a useful point of view.</p></div><div className="grid gap-5 lg:grid-cols-3">{projects.map((project) => { const Icon = project.icon; return <article key={project.number} className="group flex min-h-[440px] flex-col neo-border neo-shadow bg-card p-6 transition-transform hover:-translate-y-2"><div className="flex items-center justify-between font-mono text-xs text-muted-foreground"><span>{project.number}</span><Icon className="size-5 text-accent" /></div><div className={`mt-10 flex size-16 items-center justify-center rounded-full ${project.tone} text-primary`}><Icon className="size-7" /></div><p className="mt-8 font-mono text-[10px] uppercase tracking-[0.18em] text-accent">{project.type}</p><h3 className="mt-3 text-2xl font-semibold leading-tight text-primary">{project.title}</h3><p className="mt-4 text-sm leading-6 text-muted-foreground">{project.description}</p><div className="mt-auto border-t border-border pt-5"><div className="flex items-end justify-between"><div><p className="text-3xl font-semibold text-primary">{project.metric}</p><p className="mt-1 font-mono text-[10px] uppercase tracking-[0.15em] text-muted-foreground">{project.metricLabel}</p></div><ArrowUpRight className="size-5 text-accent transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></div><div className="mt-5 flex flex-wrap gap-2">{project.tags.map((tag) => <span key={tag} className="rounded-full border border-border px-3 py-1 font-mono text-[10px] text-muted-foreground">{tag}</span>)}</div></div></article> })}</div></section>
}
